/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LinearCutpackage;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomi
 */

    
public class Login extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    String felhasznalo;
    String jelszo;
    
    
    public Login() {
        initComponents();
        this.felhasznalo = txtFelhasznalo.getText();
        this.jelszo = txtJelszo.getText();
        this.setLocationRelativeTo(null); // középre igazítja az ablakot
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnLoginBelep = new javax.swing.JToggleButton();
        btnUjFelhasznalo = new javax.swing.JToggleButton();
        txtFelhasznalo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLoginKilep = new javax.swing.JButton();
        txtJelszo = new javax.swing.JPasswordField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLoginBelep.setText("Belépés");
        btnLoginBelep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginBelepActionPerformed(evt);
            }
        });

        btnUjFelhasznalo.setText("Új felhasználó");
        btnUjFelhasznalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjFelhasznaloActionPerformed(evt);
            }
        });

        jLabel1.setText("Felhasználónév:");

        jLabel2.setText("Jelszó:");

        btnLoginKilep.setText("Kilépés");
        btnLoginKilep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginKilepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJelszo, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtFelhasznalo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoginKilep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUjFelhasznalo)
                    .addComponent(btnLoginBelep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFelhasznalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJelszo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnLoginBelep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUjFelhasznalo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoginKilep)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginKilepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginKilepActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnLoginKilepActionPerformed

    private void btnUjFelhasznaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjFelhasznaloActionPerformed
        // TODO add your handling code here:
        
        Registration newRegistration = new Registration();
        newRegistration.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnUjFelhasznaloActionPerformed

    private void btnLoginBelepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginBelepActionPerformed
        // TODO add your handling code here:

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "");
            Statement st = conn.createStatement();
            ResultSet rs=st.executeQuery("select * from users where felhasznalo='"+felhasznalo+"' and jelszo='"+jelszo+"'");
            felhasznalo=txtFelhasznalo.getText();
            jelszo=txtJelszo.getText();
            int count = 0;
            while (rs.next()) {                
                count++;
            }
            
            if (felhasznalo.equals("") && jelszo.equals("")) 
            {
                JOptionPane.showMessageDialog(null, "Írd be felhasználóneved és jelszavad!", "ERROR", JOptionPane.ERROR_MESSAGE);
            } 
            else if (count >0)
            {
                
                System.out.println("Bejelentkezés sikeres!");
                this.dispose();
                Main newMain = new Main();
                newMain.setVisible(true);

            }
            else{
            txtFelhasznalo.setText("");
            txtJelszo.setText("");
                JOptionPane.showMessageDialog(null, "Hibás felhanálónév vagy jelszó!");
            
            }
            
            
        } catch (HeadlessException | SQLException e) {
        }
        
        
        
    }//GEN-LAST:event_btnLoginBelepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLoginBelep;
    private javax.swing.JButton btnLoginKilep;
    private javax.swing.JToggleButton btnUjFelhasznalo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFelhasznalo;
    private javax.swing.JPasswordField txtJelszo;
    // End of variables declaration//GEN-END:variables
}
