/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LinearCutpackage;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Tomi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    String host = "jdbc:mysql://localhost:3306/szelvenyek";
    String user = "root";
    String password = "";
    DefaultTableModel model;
    String munkaszam;
    String szeles;
    String mag;
    String falv;
    String hosszu;
    String db;
    
    
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdatok = new javax.swing.JTable();
        cbSzelesseg = new javax.swing.JComboBox<>();
        cbMagassag = new javax.swing.JComboBox<>();
        cbFalvastagsag = new javax.swing.JComboBox<>();
        txtHossz = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHozzaad = new javax.swing.JButton();
        btnKilep = new javax.swing.JButton();
        txtMunkaszam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblBejelentkezett = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDarabszam = new javax.swing.JTextField();
        btnMunkalapGen = new javax.swing.JButton();
        btnSorTorol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LinearCut ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblAdatok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Szélesség (mm)", "Magasság (mm)", "Falvastagság (mm)", "Hossz (mm)", "Darabszám"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdatok.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblAdatok.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblAdatok);

        jLabel1.setText("Szélesség (mm)");

        jLabel2.setText("Magasság (mm)");

        jLabel3.setText("Falvastagság (mm)");

        jLabel4.setText("Hossz (mm)");

        btnHozzaad.setText("Hozzáadás");
        btnHozzaad.setEnabled(false);
        btnHozzaad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHozzaadActionPerformed(evt);
            }
        });

        btnKilep.setText("Kilépés");
        btnKilep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKilepActionPerformed(evt);
            }
        });

        txtMunkaszam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMunkaszamKeyReleased(evt);
            }
        });

        jLabel5.setText("Munkaszám:");

        jLabel6.setText("Darabszám");

        btnMunkalapGen.setText("Munkalap generálása");
        btnMunkalapGen.setEnabled(false);
        btnMunkalapGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunkalapGenActionPerformed(evt);
            }
        });

        btnSorTorol.setText("Sor törlése");
        btnSorTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorTorolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnHozzaad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnMunkalapGen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSorTorol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnKilep, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbSzelesseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbMagassag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbFalvastagsag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtHossz, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtDarabszam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(txtMunkaszam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(428, 428, 428))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblBejelentkezett, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtMunkaszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBejelentkezett, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSzelesseg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMagassag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFalvastagsag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHossz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDarabszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHozzaad)
                    .addComponent(btnMunkalapGen)
                    .addComponent(btnSorTorol))
                .addGap(18, 18, 18)
                .addComponent(btnKilep)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKilepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKilepActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login ujLogin = new Login();
        ujLogin.setVisible(true);
    }//GEN-LAST:event_btnKilepActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:

            Connection conn = DriverManager.getConnection(host, user, password);
            String sql = "SELECT szelesseg, magassag, falvastagsag, kgpermm, cikkszam FROM szelvenyek";
            Statement sta = conn.createStatement();
            ResultSet rs = sta.executeQuery(sql);
            while (rs.next()) {                
                cbSzelesseg.addItem(rs.getString("szelesseg"));
                cbMagassag.addItem(rs.getString("magassag"));
                cbFalvastagsag.addItem(rs.getString("falvastagsag"));
            }
            sta.close();
            conn.close();
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hiba!" +ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnHozzaadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHozzaadActionPerformed
        // TODO add your handling code here:
        
        SorHozzaAd(cbSzelesseg.getSelectedItem().toString(), cbMagassag.getSelectedItem().toString(), cbFalvastagsag.getSelectedItem().toString(), txtHossz.getText(), txtDarabszam.getText());
        
    }//GEN-LAST:event_btnHozzaadActionPerformed

    private void btnMunkalapGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunkalapGenActionPerformed
        // TODO add your handling code here:
        
        munkaszam = txtMunkaszam.getText();
        
        Document document = new Document();
        try {
            String file = "C:\\Users\\Public\\Documents\\"+munkaszam+".pdf";
            PdfWriter.getInstance(document,
            new FileOutputStream(file));

            document.open();
            
            PdfPTable fejlec = new PdfPTable(1);
            PdfPCell cell1 = new PdfPCell(new Paragraph("Darabolási munkalap\n"+munkaszam+""));
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell1.setBorder(PdfPCell.NO_BORDER);
            
            PdfPTable cim = new PdfPTable(5);
            PdfPCell cimcellc0 = new PdfPCell(new Paragraph("Szélesség (mm)"));
            PdfPCell cimcellc1 = new PdfPCell(new Paragraph("Magasság (mm)"));
            PdfPCell cimcellc2 = new PdfPCell(new Paragraph("Falvastagság (mm)"));
            PdfPCell cimcellc3 = new PdfPCell(new Paragraph("Hossz \n(mm)"));
            PdfPCell cimcellc4 = new PdfPCell(new Paragraph("Darabszám (db)"));
            
            cimcellc0.setBorder(PdfPCell.NO_BORDER);
            cimcellc1.setBorder(PdfPCell.NO_BORDER);
            cimcellc2.setBorder(PdfPCell.NO_BORDER);
            cimcellc3.setBorder(PdfPCell.NO_BORDER);
            cimcellc4.setBorder(PdfPCell.NO_BORDER);
            
            cimcellc0.setHorizontalAlignment(Element.ALIGN_CENTER);
            cimcellc1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cimcellc2.setHorizontalAlignment(Element.ALIGN_CENTER);
            cimcellc3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cimcellc4.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            cim.addCell(cimcellc0);
            cim.addCell(cimcellc1);
            cim.addCell(cimcellc2);
            cim.addCell(cimcellc3);
            cim.addCell(cimcellc4);

            cim.setSpacingBefore(30f);
            
            fejlec.addCell(cell1);
            document.add(fejlec);
            document.add(cim);

            PdfPTable table = new PdfPTable(5); // 5 oszlop.
            table.setSpacingBefore(40f);
            
            for (int row = 0; row < tblAdatok.getRowCount(); row++) {
                    for (int col = 0; col < tblAdatok.getColumnCount(); col++) {
                        
                        PdfPCell cellRow = new PdfPCell(new Paragraph((String) tblAdatok.getValueAt(row, col)));
                        cellRow.setHorizontalAlignment(Element.ALIGN_CENTER);
                        cellRow.setBorder(PdfPCell.NO_BORDER);
                        table.addCell(cellRow);
                }
            }
            
            document.add(table);
            document.close();
            JOptionPane.showMessageDialog(this, "Munkalap kész!");
        
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnMunkalapGenActionPerformed

    private void btnSorTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorTorolActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblAdatok.getModel();
        
        if (tblAdatok.getSelectedRowCount() == 1) {
            model.removeRow(tblAdatok.getSelectedRow());
        } else {
            if (tblAdatok.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Üres a táblázat!");
            } else {
                JOptionPane.showMessageDialog(this, "Válasszon ki egy sort a törléshez!");
            }
        }
        
    }//GEN-LAST:event_btnSorTorolActionPerformed

    private void txtMunkaszamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunkaszamKeyReleased
        // TODO add your handling code here:
        
        if (txtMunkaszam.getText().length() > 0) {
            btnHozzaad.setEnabled(true);
            btnMunkalapGen.setEnabled(true);
        } else {
            btnHozzaad.setEnabled(false);
            btnMunkalapGen.setEnabled(false);
        }
    }//GEN-LAST:event_txtMunkaszamKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHozzaad;
    private javax.swing.JButton btnKilep;
    private javax.swing.JButton btnMunkalapGen;
    private javax.swing.JButton btnSorTorol;
    private javax.swing.JComboBox<String> cbFalvastagsag;
    private javax.swing.JComboBox<String> cbMagassag;
    private javax.swing.JComboBox<String> cbSzelesseg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBejelentkezett;
    private javax.swing.JTable tblAdatok;
    private javax.swing.JTextField txtDarabszam;
    private javax.swing.JTextField txtHossz;
    private javax.swing.JTextField txtMunkaszam;
    // End of variables declaration//GEN-END:variables

    private void SorHozzaAd(String szelesseg, String magassag, String falvastagsag, String hossz, String darabszam)
    {
        model = (DefaultTableModel) tblAdatok.getModel();
        String[] sor = {szelesseg, magassag, falvastagsag, hossz, darabszam};
        model.addRow(sor);
        
    }
}
